// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATOr3Yg5X7qY95puVNXwsf38P12e1pH98',
    appId: '1:651543804213:web:af0b0d875974aa98c0b47c',
    messagingSenderId: '651543804213',
    projectId: 'quick-bites-a80a6',
    authDomain: 'quick-bites-a80a6.firebaseapp.com',
    storageBucket: 'quick-bites-a80a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFazHx0_b8HDQ1bVK0tk-s5Xij0hfQ6uQ',
    appId: '1:651543804213:android:d4a3c9907ef70e5ec0b47c',
    messagingSenderId: '651543804213',
    projectId: 'quick-bites-a80a6',
    storageBucket: 'quick-bites-a80a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK2Bp4yQRhR1-n0qUn5hWuGqswoO2BuDA',
    appId: '1:651543804213:ios:0318aa02f1f4e577c0b47c',
    messagingSenderId: '651543804213',
    projectId: 'quick-bites-a80a6',
    storageBucket: 'quick-bites-a80a6.appspot.com',
    iosBundleId: 'com.example.quickBites',
  );
}
